INSERT INTO libros(genero, paginas, titulo, autor_id) VALUES
('Novela', 320, 'La sombra del eco', 1),
('Ciencia Ficción', 280, 'Horizonte Infinito', 2),
('Fantasía', 450, 'El Reino de Bruma', 3),
('Romance', 210, 'Bajo la misma lluvia', 4),
('Misterio', 310, 'El último susurro', 5),
('Aventura', 390, 'Rumbo al norte', 6),
('Drama', 275, 'Cicatrices del alma', 7),
('Histórica', 430, 'La corona olvidada', 8),
('Poesía', 120, 'Versos al viento', 9),
('Thriller', 340, 'Código fantasma', 10),
('Infantil', 80, 'Las aventuras de Nico', 11),
('Juvenil', 200, 'El club del sótano', 12),
('Biografía', 360, 'Viviendo dos veces', 13),
('Ensayo', 150, 'Pensar el caos', 14),
('Novela', 290, 'El jardín secreto', 15),
('Ciencia Ficción', 310, 'Neón en la oscuridad', 16),
('Fantasía', 470, 'Los dragones del alba', 17),
('Romance', 220, 'Cartas sin destino', 18),
('Misterio', 305, 'La ventana cerrada', 19),
('Aventura', 380, 'Más allá del fin', 20),
('Drama', 265, 'El precio de la verdad', 1),
('Histórica', 410, 'La dama del tiempo', 2),
('Poesía', 100, 'Mar y tinta', 3),
('Thriller', 330, 'Ojos en la niebla', 4),
('Infantil', 90, 'Leo y su cometa', 5),
('Juvenil', 190, 'Los cinco del parque', 6),
('Biografía', 345, 'Caminar sin mapa', 7),
('Ensayo', 170, 'Humanos y máquinas', 8),
('Novela', 300, 'Ecos de invierno', 9),
('Ciencia Ficción', 295, 'Planeta oscuro', 10),
('Fantasía', 440, 'El conjuro perdido', 11),
('Romance', 230, 'Te vi en abril', 12),
('Misterio', 320, 'Sombras de cristal', 13),
('Aventura', 370, 'Río salvaje', 14),
('Drama', 250, 'Entre luces y sombras', 15),
('Histórica', 400, 'El general sin nombre', 16),
('Poesía', 130, 'Alas de papel', 17),
('Thriller', 350, 'El impostor', 18),
('Infantil', 85, 'Clara y la luna', 19),
('Juvenil', 210, 'Puertas paralelas', 20);


INSERT INTO autores(nombre, nacionalidad, apellido) VALUES
('Carlos', 'Mexicana', 'Ramírez'),
('Lucía', 'Argentina', 'Fernández'),
('Mateo', 'Chilena', 'Pérez'),
('Isabela', 'Colombiana', 'Gómez'),
('Julián', 'Peruana', 'Rojas'),
('Camila', 'Uruguaya', 'Díaz'),
('Sofía', 'Española', 'Martínez'),
('Andrés', 'Venezolana', 'Torres'),
('Valentina', 'Ecuatoriana', 'Castro'),
('Sebastián', 'Boliviana', 'Navarro'),
('Elena', 'Cubana', 'Mendoza'),
('Tomás', 'Paraguaya', 'Vega'),
('Renata', 'Costarricense', 'Morales'),
('Emilio', 'Panameña', 'Herrera'),
('Mariana', 'Hondureña', 'Suárez'),
('Nicolás', 'Salvadoreña', 'Cano'),
('Paula', 'Guatemalteca', 'Aguilar'),
('Gabriel', 'Dominicana', 'Ortega'),
('Ana', 'Nicaragüense', 'Delgado'),
('Lorenzo', 'Puertorriqueña', 'Silva');

SELECT * FROM autores;