version: '3.8'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql-hibernate
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hibernate_db
      MYSQL_USER: hibernate_user
      MYSQL_PASSWORD: hibernate_password
    ports:
      - "9010:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hibernate-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  hibernate-network:
    driver: bridge
